# Generated by Django 5.0.6 on 2025-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активно'), ('CLOSED', 'Закрыто'), ('ARCHIVED', 'В архиве')], default='ACTIVE', max_length=20, verbose_name='Статус объявления'),
        ),
    ]
